#!/usr/bin/env python3
"""View the PGM occupancy map with room polygons and names overlaid.

Outputs:
    map_walls.png       — walls only (generated by convert_floorplan.py)
    map_rooms_labeled.png — walls + room regions and labels (this script)

Usage:
    python view_pgm_rooms.py dataset/White_House_West_Wing/floor_1
    python view_pgm_rooms.py dataset/White_House_West_Wing/floor_1 --output map_rooms_labeled.png
"""

import argparse
import os

import cv2
import numpy as np
import yaml


def load_floor_data(floor_dir):
    """Load map.pgm, map.yaml, waypoints.yaml from floor_dir. Returns (pgm_bgr, resolution, waypoints) or (None, None, None)."""
    pgm_path = os.path.join(floor_dir, "map.pgm")
    yaml_path = os.path.join(floor_dir, "map.yaml")
    wp_path = os.path.join(floor_dir, "waypoints.yaml")

    if not os.path.isfile(pgm_path):
        print(f"  Not found: {pgm_path}")
        return None, None, None

    pgm = cv2.imread(pgm_path, cv2.IMREAD_GRAYSCALE)
    if pgm is None:
        print(f"  Could not load: {pgm_path}")
        return None, None, None

    resolution = 0.05
    if os.path.isfile(yaml_path):
        with open(yaml_path) as f:
            cfg = yaml.safe_load(f)
            resolution = float(cfg.get("resolution", resolution))

    waypoints = []
    if os.path.isfile(wp_path):
        with open(wp_path) as f:
            data = yaml.safe_load(f)
            waypoints = data.get("waypoints") or []
    print(f"  Loaded {len(waypoints)} rooms from {os.path.basename(floor_dir)}")

    # PGM to BGR: white=free, black=walls, 128=doors (brown)
    bgr = np.zeros((*pgm.shape[:2], 3), dtype=np.uint8)
    bgr[:] = (255, 255, 255)  # free
    bgr[pgm <= 1] = (0, 0, 0)   # wall
    door_mask = (pgm >= 126) & (pgm <= 130)
    bgr[door_mask] = (42, 42, 139)   # brown in BGR
    return bgr, resolution, waypoints


def _distinct_colors(n):
    """Generate n visually distinct BGR colors using golden-angle hue spacing."""
    colors = []
    for i in range(n):
        hue = int((i * 137.508) % 180)
        hsv = np.uint8([[[hue, 180, 210]]])
        bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)[0, 0]
        colors.append(tuple(int(c) for c in bgr))
    return colors


def draw_rooms_view(floor_dir, output_path=None):
    """Draw PGM with filled room polygons, outlines, and names overlaid."""
    bgr, resolution, waypoints = load_floor_data(floor_dir)
    if bgr is None:
        return None

    h, w = bgr.shape[:2]

    def meter_to_pixel(x_m, y_m):
        col = int(round(x_m / resolution))
        row = int(round(y_m / resolution))
        return (col, row)

    colors = _distinct_colors(max(len(waypoints), 1))

    # Pass 1: draw semi-transparent filled polygons
    fill_overlay = bgr.copy()
    for i, wp in enumerate(waypoints):
        polygon = wp.get("polygon") or []
        if len(polygon) < 3:
            continue
        pts = np.array([meter_to_pixel(p[0], p[1]) for p in polygon], dtype=np.int32)
        cv2.fillPoly(fill_overlay, [pts], colors[i])
    cv2.addWeighted(fill_overlay, 0.25, bgr, 0.75, 0, bgr)

    # Pass 2: draw polygon outlines (solid, on top of the blend)
    for i, wp in enumerate(waypoints):
        polygon = wp.get("polygon") or []
        if len(polygon) < 3:
            continue
        pts = np.array([meter_to_pixel(p[0], p[1]) for p in polygon], dtype=np.int32)
        cv2.polylines(bgr, [pts], isClosed=True, color=colors[i], thickness=2, lineType=cv2.LINE_AA)

    # Pass 3: draw labels with background boxes
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = max(0.35, min(0.55, w / 2500))
    for i, wp in enumerate(waypoints):
        name = wp.get("name", "?")
        cx, cy = meter_to_pixel(wp.get("x", 0), wp.get("y", 0))
        cx = max(0, min(w - 1, cx))
        cy = max(0, min(h - 1, cy))
        (tw, th), baseline = cv2.getTextSize(name, font, font_scale, 1)
        tx = cx - tw // 2
        ty = cy + th // 2
        pad = 3
        cv2.rectangle(bgr, (tx - pad, ty - th - pad), (tx + tw + pad, ty + baseline + pad),
                       (0, 0, 0), -1)
        cv2.putText(bgr, name, (tx, ty), font, font_scale,
                     (255, 255, 255), 1, cv2.LINE_AA)

    if output_path:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        cv2.imwrite(output_path, bgr)
        print(f"  Saved: {output_path}")

    show_window = not output_path
    if show_window:
        try:
            cv2.imshow("PGM with rooms", bgr)
            print("  Close the window to exit.")
            cv2.waitKey(0)
            cv2.destroyAllWindows()
        except Exception:
            default_path = os.path.join(floor_dir, "map_rooms_labeled.png")
            cv2.imwrite(default_path, bgr)
            print(f"  No display; saved to {default_path}")
    return bgr


def main():
    parser = argparse.ArgumentParser(description="View PGM map with room polygons and names")
    parser.add_argument("floor_dir", help="Floor directory (e.g. dataset/Hotel/floor_1)")
    parser.add_argument("--output", "-o", help="Save view to this image path")
    args = parser.parse_args()

    if not os.path.isdir(args.floor_dir):
        print(f"Not a directory: {args.floor_dir}")
        return

    draw_rooms_view(args.floor_dir, output_path=args.output)


if __name__ == "__main__":
    main()
